version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: HelloApes66
      MYSQL_DATABASE: seed
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HelloApes66"
      MSSQL_PID: "Express"
    ports:
      - 1433:1433

  db2:
    image: ibmcom/db2:11.5.0.0
    # don't run db2 container in privileges mode as this is huge security risk
    # instead we only shared the needed IPC privileges with host
    # privileged: true
    ipc: host
    cap_add:
      - IPC_OWNER
      - IPC_LOCK
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: HelloApes66
      PERSISTENT_HOME: "false"
      DBNAME: sample
      # improve performance see docker hub
      ARCHIVE_LOGS: "false"
      AUTOCONFIG: "false"
    ports:
      - 50000:50000
      - 55000:55000
    volumes:
      - db2data:/database

  oracle11:
    image: oracle/database:11.2.0.2-xe
    shm_size: 1g
    environment:
      ORACLE_PWD: HelloApes66
    volumes:
      - oracle11data:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 8080
      - 5500

  oracle12:
    image: oracle/database:12.2.0.1-se2
    labels:
      - "oracle"
    shm_size: 1g
    environment:
      ORACLE_PWD: HelloApes66
    volumes:
      - oracle12data:/opt/oracle/oradata
      - ./scripts/oracle12:/opt/oracle/scripts/setup
    ports:
      - 1522:1521
      - 5500

  adminer:
    image: adminer
    ports:
      - 5050:8080

volumes:
  oracle12data:
  oracle11data:
  mysqldata:
  db2data:
  db2dataremote:
