version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloape
    volumes:
       - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: HelloApes66
      MYSQL_DATABASE: seed
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
#    volumes:
#      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: HelloApes66
      MSSQL_PID: Express
    ports:
      - 1433:1433

  db2:
    image: ibmcom/db2express-c:latest
    container_name: db2
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: HelloApes66
    command: db2start
    ports:
      - 50000:50000
      - 55000:55000
    volumes:
      - ./scripts/db2/entrypoint.sh:/entrypoint.sh
      - db2data:/share

  db2remote:
    image: ibmcom/db2express-c:latest
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: HelloApes66
    command: db2start
    ports:
      - 50000
      - 55000
    volumes:
      - db2dataremote:/share

  oracle11:
    image: oracle/database:11.2.0.2-xe
    shm_size: 1g
    environment:
      ORACLE_PWD: HelloApes66
    volumes:
      - ./oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 8080
      - 5500

  oracle12:
    image: oracle/database:12.2.0.1-se2
    labels:
      - "oracle"
    shm_size: 1g
    environment:
      ORACLE_PWD: HelloApes66
    volumes:
      - oracle12data:/opt/oracle/oradata
      - ./scripts/oracle12:/opt/oracle/scripts/setup
    ports:
      - 1522:1521
      - 5500

  adminer:
    image: adminer
    ports:
      - 5050:8080

volumes:
  data:
  oracle12data:
  mysqldata:
  db2data:
  db2dataremote:
